import os, shutil, glob
# os.system('notepad')
# os.system('python')
# os.mkdir("D:\\Python\\MyOwnPractices\\python\\WeekFour\\dirusingoscom")
# os.rename("D:\\Python\\MyOwnPractices\\python\\WeekFour\\dirusingoscom", "D:\\Python\\MyOwnPractices\\python\\WeekFour\\simpleos")
# fd = os.open("movable.py",os.O_CREAT)
# os.close(fd)
# shutil.move("movable.py","simpleos")
# txt = os.open("Test.txt",os.O_CREAT)
# os.close(txt)
# filelist1 = glob.glob("*.py")
# filelist2 = glob.glob("*.txt")
# print(filelist1)
# print(filelist2)
# str1 = "\n".join(filelist1)
# str2 = "\n".join(filelist2)
# print(str1)
# print(str2)