from tkinter import *
# # window = Tk()
# # window.title("Welcome to all! ")
# # window.geometry('100x100')
# # print("Before mainloop")
# # window.mainloop()
# # print("After mainloop")
# window = Tk()
# window.title("Welcome ot Hps app")
# lbl = Label(window,text ="Welcome to all")
# lbl.grid(column=1,row=1,padx=50, pady=50)
# window.geometry('300x300')
# window.mainloop()
# window = Tk()
# window.title("Welcome to all")
# lbl1 = Label(window,text="Enter first Name: ")
# en1 = Entry(window)
# lbl1.grid(column=0, row=0,padx= 20,pady=20)
# en1.grid(column=1,row=0)

# lbl2 = Label(window,text="Enter Second Name: ")
# en2 = Entry(window)
# lbl2.grid(column=0, row=1)
# en2.grid(column=1,row=1)

# but1 = Button(window,text="Submit")
# but2 = Button(window,text="Reset")
# but1.grid(column = 0, row=2)
# but2.grid(column = 1, row=2)

# lbl3 = Label(window,text="Result: ")
# en3 = Entry(window)
# lbl3.grid(column = 0, row=4)
# en3.grid(column=1,row=4)
# window.geometry('350x350')

# window.mainloop()