f = open("D:\\Python\\MyOwnPractices\\python\\Week5\\binary.txt", "wb")
text  = (input("Please input any string: "))
num = int(input("Please enter any number: "))
num_b = bin(num)

to_binary = text.encode("utf-8")
f.write(to_binary)
f.write(b"\n")
f.write(num_b.encode())
print(to_binary)
print(num_b)
f.close()